### PR TITLE
Added browserify field to allow JSX parsing as a submodule

### LINKED ISSUE #3: Can't require
I'm having issues requiring instatype, and I have no idea why. When I use the normal `src/js/app.js` file, my browserify build breaks on the first `return ( <div /> )`, like it can't deal with `<`. When I use `build/js/app.js`, I get an error where it can't find `EventConstants.js` in React, which is bollocks because it can. 

Any ideas?

### PR DESCRIPTION
**Pull request by RichardLitt**
closes #3

### CODE REVIEW

**Comment by gragland** [comment]
So the browserify field had to be removed because it was causing the "bundle" script in package.json to fail. Instead you should just run the "bundle" script (which uses browserify + babelify transform) or the "watch" script to have it bundled automatically.

**Comment by RichardLitt** [comment]
Wait, so your reverted this commit?

**Comment by gragland** [comment]
Changed back in this <a href="https://github.com/gragland/instatype/commit/efd2785f8c3d31cf3bb96a71f16b0c774e0a6bca">recent commit</a>, although I suppose reverting it might have made more sense. I'm new at this..

**Comment by RichardLitt** [comment]
No worries. I submitted another PR in #6 - this fixes the issue with the bundle breaking. Should be good now.

**Pull request merged**
